### ISSUE TITLE
Cloud service

### ISSUE THREAD

**Issue by imSunnyk** [shivang8/Secure-File-Storage-Using-Hybrid-Cryptography#3]
Could u plz tell me which cloud service you have used in this project to store data?

**Comment by shivang8** [comment]
I used Amazon EC2

**Comment by imSunnyk** [comment]
If this project is used with other cloud service, do I have to change something in code?

**Comment by imSunnyk** [comment]
Hi Shivang,

I wanted to know that have you used both cryptography and steganography.....in this project
